/**
 * Which argument indices of a given WebGL method are GLenum-valued, per the
 * spec IDL. Used to decode numeric args to their constant name based on
 * *position*, not by guessing from the value — GL enums overlap heavily
 * (0 is simultaneously NONE, ZERO, POINTS and FALSE), so guessing from a bare
 * number alone misfires constantly on ordinary integers like viewport
 * coordinates. Not exhaustive; methods/positions not listed here are simply
 * displayed as plain numbers, which is always a safe fallback.
 */
export const ENUM_ARG_INDEX: Record<string, number[]> = {
  activeTexture: [0],
  bindBuffer: [0],
  bindFramebuffer: [0],
  bindRenderbuffer: [0],
  bindTexture: [0],
  blendEquation: [0],
  blendEquationSeparate: [0, 1],
  blendFunc: [0, 1],
  blendFuncSeparate: [0, 1, 2, 3],
  bufferData: [0, 2],
  bufferSubData: [0],
  checkFramebufferStatus: [0],
  compressedTexImage2D: [0, 2],
  compressedTexSubImage2D: [0, 6],
  copyTexImage2D: [0, 2],
  copyTexSubImage2D: [0],
  createShader: [0],
  cullFace: [0],
  depthFunc: [0],
  disable: [0],
  drawArrays: [0],
  drawElements: [0, 2],
  enable: [0],
  framebufferRenderbuffer: [0, 1, 2],
  framebufferTexture2D: [0, 1, 2],
  frontFace: [0],
  generateMipmap: [0],
  getBufferParameter: [0, 1],
  getFramebufferAttachmentParameter: [0, 1, 2],
  getParameter: [0],
  getProgramParameter: [1],
  getRenderbufferParameter: [0, 1],
  getShaderParameter: [1],
  getShaderPrecisionFormat: [0, 1],
  getTexParameter: [0, 1],
  getVertexAttrib: [1],
  hint: [0, 1],
  isEnabled: [0],
  pixelStorei: [0],
  readPixels: [4, 5],
  renderbufferStorage: [0, 1],
  stencilFunc: [0],
  stencilFuncSeparate: [0, 1],
  stencilMaskSeparate: [0],
  stencilOp: [0, 1, 2],
  stencilOpSeparate: [0, 1, 2, 3],
  texImage2D: [0, 2, 6, 7],
  texParameterf: [0, 1],
  texParameteri: [0, 1, 2],
  texSubImage2D: [0, 6, 7],
  vertexAttribPointer: [2],

  // WebGL2
  bindBufferBase: [0],
  bindBufferRange: [0],
  bindTransformFeedback: [0],
  blitFramebuffer: [9],
  clientWaitSync: [1],
  copyBufferSubData: [0, 1],
  copyTexSubImage3D: [0],
  drawArraysInstanced: [0],
  drawElementsInstanced: [0, 2],
  drawRangeElements: [0, 4],
  framebufferTextureLayer: [0, 1],
  getIndexedParameter: [0],
  getInternalformatParameter: [0, 1, 2],
  getQuery: [0, 1],
  getQueryParameter: [1],
  getSamplerParameter: [1],
  getSyncParameter: [1],
  invalidateFramebuffer: [0],
  invalidateSubFramebuffer: [0],
  readBuffer: [0],
  renderbufferStorageMultisample: [0, 1],
  samplerParameterf: [1],
  samplerParameteri: [1, 2],
  texImage3D: [0, 2, 7, 8],
  texStorage2D: [0, 1],
  texStorage3D: [0, 1],
  texSubImage3D: [0, 8, 9],
  vertexAttribIPointer: [2],
  waitSync: [1],
};

/** Method results that are themselves a single GLenum value, worth decoding. */
export const ENUM_RESULT_METHODS = new Set(['getError', 'checkFramebufferStatus', 'clientWaitSync']);
